### ISSUE TITLE
Look at difference between slopes for NII and Ha in the case of 30 Dor

### ISSUE THREAD

**Issue by will-henney** [JavGVastro/PhD.Paper#12]
In theory, the difference between the slopes of the N II and H alpha structure functions will allow us to estimate the term $\delta\kappa$ from Brunt & Mac Low (2004). 

I already have this for [N II] from Arthur et al. 

It would be good to get it for 30 Dor also.  The problem with the current results is that there is a degeneracy with the seeing width for both lines.  Therefore, it is important to use the same s0 for both. 

So @JavGVastro could you please run another analysis like ci-MUSE-Dor-N.ipynb but with the seeing width fixed at the value found for Ha

H alpha
![CleanShot 2022-11-29 at 13 37 40@2x](https://user-images.githubusercontent.com/161264/204631333-f757958b-3d54-42ff-b70a-32986f099897.jpg)

[N II]
![CleanShot 2022-11-29 at 13 38 35@2x](https://user-images.githubusercontent.com/161264/204631525-67c01c57-b868-414f-a29e-e39bb734a5f3.jpg)

**Comment by JavGVastro** [comment]
Results of 30 Dor [NII] line using a fixed value of s0 (from Ha analysis).

![firefox_VxDHPHtZKw](https://user-images.githubusercontent.com/53878105/204707536-af8625ba-66fc-4887-a2a7-1abea733d857.png)
![firefox_PymmEGVQj8](https://user-images.githubusercontent.com/53878105/204707606-66c1a3b3-ab3b-499e-a811-3d9e0771900d.png)

**Comment by will-henney** [comment]
In the end, I decided not to include this in the paper because the results are not as clear as I had hoped!
