### ISSUE TITLE
Small  change to dot-dashed line in Figure 10

### ISSUE THREAD

**Issue by will-henney** [JavGVastro/PhD.Paper#13]
![CleanShot 2022-12-12 at 11 05 30](https://user-images.githubusercontent.com/161264/207108719-b1a30991-aee6-4212-af96-53198324caee.jpg)

I think the curve where vexp and sigpos are added in quadrature would be better with a higher value of vexp.  Could you please try with vexp = 10 or 12, and see what value fits best

**Comment by JavGVastro** [comment]
How about something like this? Limits of the shaded area are between 8 and 12 km/s.
Also I added Arthur et al. 2016 to the legend so the 3 explanations about sig_los vs sig_pos are in the figure.

[corr-los-vs-pos.pdf](https://github.com/JavGVastro/PhD.Paper/files/10210870/corr-los-vs-pos.pdf)

**Comment by will-henney** [comment]
Yes, that is perfect. Thank you
