### ISSUE TITLE
Cleaner version of Figure A1b

### ISSUE THREAD

**Issue by will-henney** [JavGVastro/PhD.Paper#14]
![CleanShot 2022-12-13 at 13 15 30@2x](https://user-images.githubusercontent.com/161264/207424584-0b57aa5c-8490-4d10-9379-0b1f9e2f7111.jpg)

In this figure, I think it would be better without all the dotted lines.  It is not necessary to include them since the same information is given in Fig A2a

**Comment by JavGVastro** [comment]
Ok. I'll add a clenaer version of this plot.
Reviewing the orignal files there are two versions:
The original without all the lines and and updated version

![original](https://user-images.githubusercontent.com/53878105/207446563-5f6efa58-7428-4343-8be4-422f26e28938.png)

![upDATED](https://user-images.githubusercontent.com/53878105/207446663-13a40085-0282-41d7-920e-3104868af439.png)

**Comment by will-henney** [comment]
This is now fixed in the paper
