### ISSUE TITLE
Change some values to upper limits in Table 2

### ISSUE THREAD

**Issue by will-henney** [JavGVastro/PhD.Paper#8]
Any value that is less than 2 times the negative sigma should be replaced with an upper limit of value plus 2 times positive sigma (95% confidence limit).

For example s0(FWHM) for NGC 595: 0.20 (-0.16) (+0.38)

* Value 0.20 is less than 2 x 0.16
* Therefore, replace with upper limit: 0.20 + 2 x 0.38 = 0.96

**Comment by will-henney** [comment]
I just noticed that in the figure caption it says

> Confidence intervals are up to 2-sigma of the posteriors.

If this is true, then my example is wrong because the value is more than 2 sigma above zero.

**Comment by JavGVastro** [comment]
For the uncertaintites I choose to use the values that match the light translucent boxes in the structure function plots, which correspond to the range [2.5 , 97.5].

Following N595 s0 (FWHM) example, the range is [0.01 , 0.53] with a median of 0.17. Which gives 0.17 (-0.16) (+0.36). 
This procedure was used for all regions and parameters.
If this needs any change let me know.

**Comment by will-henney** [comment]
I have now edited Table 3 of paper to include upper limits in all the appropriate places I think
