### ISSUE TITLE
Some of the MCMC runs may not have converged

### ISSUE THREAD

**Issue by will-henney** [JavGVastro/PhD.Paper#9]
I am writing the description of the MCMC estimation of the parameter uncertainties. 

The original plan was to use chain lengths that were at least 50 times the autocorrelation time, to ensure that the walkers have converged.  I have just done some checks that this is satisfied:

For Orion we used 5000 and the autocorrelation times are all less than 60, so that is OK. 

For 30 Dor we used 10000 and autocorrelation times are less than about 100, also OK.

For Hubble X we used 5000 and autocorrelation times are as high as 270, so **not OK**. We should use at least 150000 and retry it.  Note that the acceptance fraction is also very low in this case (around 0.35), which also indicates that we probably haven't converged. 

Please check all the other sources to make sure they satisfy the criterion.

**Comment by JavGVastro** [comment]
Here I made a table for the walkers/autocorrelation-time ratio and the acceptance fraction showing that most regions, besides HX (as previously mentioned) and the EON, comply with the criterion.
For the previous regions the calculations haven't converged yet.
The values shown are from the confidence intervals determinations used in the current results showed in the paper.
Any ratio value that may need a re-run let me know.

Region | Walkers/autocorrelation-time | Acceptance fraction
Carina | 5000 / 62 = 80                      | 0.49 
30Dor | 5000 / 73 = 68                      | 0.54 
HV      | 15 000 / 241 = 62                 | 0.44 
HX      | Still running
M8     | 10 000 / 100 = 100                | 0.48
346    | 5 000 / 57 = 87                      | 0.53
595    | 25 000 / 66 = 380                  | 0.54   
604    | 25 000 / 120 = 206                | 0.47
EON   | Still running
Orion | 5 000 / 57 = 87                      | 0.55

**Comment by will-henney** [comment]
This seems to be resolved now.
